### ISSUE TITLE
Differentiate between Windows, Linux and MacOS

### ISSUE THREAD

**Issue by lostprophet** [Emersont1/itchio#10]
Is there any way to differentiate between Windows, Linux and MacOS versions?
For example if I want to download all Windows versions of all games (since I don't use Linux or MacOS)?

Currently as I see it really downloads everything, even if I don't need Linux or MacOS.

**Comment by Emersont1** [comment]
I don't think so - I'll have to check the API, It was designed as a way to archive the downloads onto my NAS to just take all the downloadables for a product

**Comment by Emersont1** [comment]
Okay, having had a look at the API output, that's eminently doable, I'll open a PR in the next couple of days looking at this

in short, it'll be looking at the traits

```json
[
    {
        "filename": "Skelerun-Win.zip",
        "size": 61275923,
        "id": 3007740,
        "storage": "hosted",
        "traits": [
            "p_windows"
        ],
        "game_id": 747607,
        "updated_at": "2020-11-23T23:21:48.000000000Z",
        "md5_hash": "824f00808df1532917e8e89550dd66bd",
        "position": 0,
        "created_at": "2020-11-23T22:44:14.000000000Z",
        "type": "default"
    },
    {
        "filename": "Skelerun-Mac.zip",
        "size": 62800229,
        "id": 3007741,
        "storage": "hosted",
        "traits": [
            "p_osx"
        ],
        "game_id": 747607,
        "updated_at": "2020-11-23T23:21:48.000000000Z",
        "md5_hash": "57edc9b88461c8b158531a9269b9560a",
        "position": 1,
        "created_at": "2020-11-23T22:44:23.000000000Z",
        "type": "default"
    },
    {
        "filename": "Skelerun-Lin.zip",
        "size": 62281140,
        "id": 3007742,
        "storage": "hosted",
        "traits": [
            "p_linux"
        ],
        "game_id": 747607,
        "updated_at": "2020-11-23T23:21:48.000000000Z",
        "md5_hash": "49808bb81c90647f37333853e2eee7c2",
        "position": 2,
        "created_at": "2020-11-23T22:44:26.000000000Z",
        "type": "default"
    }
]
```

which is blank if multiplatform or `p_` followed by the operating system

**Comment by lostprophet** [comment]
Wow, awesome, thank you very much for checking :)

**Comment by lroellin** [comment]
@Emersont1 a suggestion as I had some thoughts about this already. I see 2 use cases that differ by how to go with non-digital stuff (or non-platform specific stuff)

- People who want to download everything that's for Windows (Win only)
- People who want to download everything but exclude anything not for their OS (Win only + all other non-specific stuff)

Hopefully you get what I mean :) maybe you can differentiate between the 2 use cases (Windows being a placeholder of course)

**Comment by Emersont1** [comment]
This has been added in line for the v2 release, I'm closing the issue
