### ISSUE TITLE
Error on processing bundle

### ISSUE THREAD

**Issue by stunlocked94** [Emersont1/itchio#16]
Hello,

i just discovered your tool and wanted to use it to process two bundles on itch.io. The Ukraine bundle went perfectly fine, after that i wanted to process the Bundle for Racial Justice.

Sadly it throws an error on processing the bundle (error1.txt) and once i try to restart it in a new cmd window it throws a different error (error2.txt).

let me know if you need more information and thank you for the tool!

Regards
[error1.txt](https://github.com/Emersont1/itchio/files/8212898/error1.txt)
[error2.txt](https://github.com/Emersont1/itchio/files/8212899/error2.txt)

**Comment by ThisIsTenou** [comment]
This looks more like a, presumably temporary, issue of the site you're trying to access rather than an issue with this tool.
```
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='demmydev.itch.io', port=443): Max retries exceeded with url: /triattack/download/Nm9d0Dw07QBr_omXG506LGQFc7qsKnyK2fEDNN0e (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020E31173550>, 'Connection to demmydev.itch.io timed out. (connect timeout=None)'))
```

The second error I got as well when itch.io was temporarly down yesterday. Do you still experience the same issue when trying again now?

**Comment by stunlocked94** [comment]
> This looks more like a, presumably temporary, issue of the site you're trying to access rather than an issue with this tool.
> 
> ```
> requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='demmydev.itch.io', port=443): Max retries exceeded with url: /triattack/download/Nm9d0Dw07QBr_omXG506LGQFc7qsKnyK2fEDNN0e (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020E31173550>, 'Connection to demmydev.itch.io timed out. (connect timeout=None)'))
> ```
> 
> The second error I got as well when itch.io was temporarly down yesterday. Do you still experience the same issue when trying again now?

sadly yes, tried it again just now. will wait until the evening and try again :)

**Comment by stunlocked94** [comment]
hello, it seems to have worked now. thank you!
