### ISSUE TITLE
Downloads not continued after cancel (e.g. ctrl-c)

### ISSUE THREAD

**Issue by DeaeLunae** [Emersont1/itchio#2]
Program thinks the existence of a file means it's completely downloaded. Maybe instead download to a temp file location, then rename to the final filename? Or catch a SIGTERM and delete the file in progress?

**Comment by Emersont1** [comment]
I have a fix i can pull in from here, I'll be on it in the next couple of days

https://github.com/Emersont1/bigfinish-ii/blob/a33ce9c582cce2fbb16a50eb1f97abbf93a45da1/src/big_finish/downloader/downloader.py#L20-L38
