### ISSUE TITLE
Downloads that are skipped are not noted in errors.txt

### ISSUE THREAD

**Issue by WAUthethird** [Emersont1/itchio#23]
Awesome tool! I'm just curious why skipped downloads aren't put in some sort of log file? Errors.txt is probably not the right place, but having this info (so I can go through and download manually) would be super helpful.

Also, the json metadata in each game folder is something I'd love to take more advantage of with a little script, so having the option to generate these folders and json for skipped/errored files without actually downloading would be great.

I'll probably write a PR for this, but would love to hear people's thoughts.

**Comment by Emersont1** [comment]
+ It skips the file if it already exists, so if you (for the sake of argument) buy another bundle, it will not re-download games already in your library to your drive
+ if you want to make the json metadata more in-depth, feel free! that sounds like a wonderful idea, it's probably worth opening a PR for the changes you want to make in the JSON format, so then we can discuss specific changes there!

Hope this helps!
