### ISSUE TITLE
Broken on Python 3.10

### ISSUE THREAD

**Issue by TheFrenchGhosty** [Emersont1/itchio#24]
Both scripts doesn't seem to work on Python 3.10:

itch-download:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/itch-download", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/itchiodl/downloader/__main__.py", line 21, in main
    l = itchiodl.LoginAPI(user, password)
  File "/home/user/.local/lib/python3.10/site-packages/itchiodl/login.py", line 29, in LoginAPI
    raise RuntimeError
RuntimeError
```

itch-load-bundle:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/itch-load-bundle", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/itchiodl/bundle_tool/__main__.py", line 12, in main
    b.load_games()
  File "/home/user/.local/lib/python3.10/site-packages/itchiodl/bundle.py", line 14, in load_games
    pages = int(s.select("span.pager_label a")[-1].text)
IndexError: list index out of range
```

Works fine on Python 3.9

**Comment by Emersont1** [comment]
I'm running python 3.10.2 on my machine and it works fine, these seem to be more issues with you logging in?

**Comment by Emersont1** [comment]
I think the first one is a duplicate of #22

I need to do some more experiments, but I think if you've not logged into the [desktop app](https://itch.io/app) before running this, it won't work.

**Comment by TheFrenchGhosty** [comment]
@Emersont1 

>I need to do some more experiments, but I think if you've not logged into the desktop app before running this, it won't work.

With Python 3.9 I don't need to login into the desktop app.

**Comment by Emersont1** [comment]
Have you tried with an API key?

**Comment by TheFrenchGhosty** [comment]
First issue doesn't appear with an API key... which is weird considering Username/Password works fine with 3.9

**Comment by Emersont1** [comment]
Username/Password works flawlessly on 3.10.2 on my machine.

**Comment by Emersont1** [comment]
![image](https://user-images.githubusercontent.com/23140112/158038207-00123927-16b4-462e-820a-ce37fca24a8c.png)
It works fine on 3.10.2, it must be an issue with your machine

**Comment by TheFrenchGhosty** [comment]
I have no idea what might be causing this honestly. I really don't know.

**Comment by Emersont1** [comment]
I've pushed v1.2.1, this should give more detail on the error. If you could post it, censoring any secret data, that would be smashing, and hopefully I can resolve this

**Comment by TheFrenchGhosty** [comment]
```
Error: success key is not true
Will print the response text (Please be careful as this may contain personal data or allow others to login to your account):
{"recaptcha_url":"https:\/\/itch.io\/captcha","success":false,"recaptcha_needed":true}
Traceback (most recent call last):
  File "/home/user/.local/bin/itch-download", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/itchiodl/downloader/__main__.py", line 25, in main
    l = itchiodl.LoginAPI(user, password)
  File "/home/user/.local/lib/python3.10/site-packages/itchiodl/login.py", line 46, in LoginAPI
    raise RuntimeError
RuntimeError
```

Here's the issue, there's a captcha.

**Comment by Emersont1** [comment]
Are you running this on a domestic IP or a datacenter IP?

**Comment by TheFrenchGhosty** [comment]
Datacenter IP

**Comment by Emersont1** [comment]
That'd be it then

**Comment by TheFrenchGhosty** [comment]
So I guess it's a non-issue, and I should just stick to API key. 

Might be nice to have `itch-load-bundle` support API key too

**Comment by Emersont1** [comment]
The Web scraper needs to be run over HTTP, so you'll have to run that on your PC

**Comment by TheFrenchGhosty** [comment]
Got it, thanks.
