### ISSUE TITLE
Crash - AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by TheFrenchGhosty** [Emersont1/itchio#28]
The download script consistently crash on this file.

```
Downloading Calico - Calico.Template.zip
Traceback (most recent call last):
  File "/home/user/.local/bin/itch-download", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/itchiodl/downloader/__main__.py", line 31, in main
    lib.download_library()
  File "/home/user/.local/lib/python3.10/site-packages/itchiodl/library.py", line 35, in download_library
    game.download(self.login)
  File "/home/user/.local/lib/python3.10/site-packages/itchiodl/game.py", line 68, in download
    itchiodl.utils.download(url, path, self.name + " - " + file)
  File "/home/user/.local/lib/python3.10/site-packages/itchiodl/utils.py", line 21, in download
    filename = re.search(r'filename="(.+)"', cd).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Emersont1** [comment]
I've had a look at this, and I can't seem to add this to my library for testing as it is free, but I'll add error checking on this to just include the name from the download name

**Comment by TheFrenchGhosty** [comment]
@Emersont1 Well, the main issue is that it crashes the script, meaning that it doesn't download what follows.

Related to https://github.com/Emersont1/itchio/issues/25

**Comment by TheFrenchGhosty** [comment]
So, I forked it ( https://github.com/TheFrenchGhosty/itchio ), and removing `.group(1)` from https://github.com/Emersont1/itchio/blob/main/itchiodl/utils.py#L21 made the download work, I then moved back to the pip package and download continued correctly, without "breaking" on this file.

What's the use of  `.group(1)` exactly? Because it doesn't seem to cause any problem from what I can see.

**Comment by Emersont1** [comment]
so the `.group(1)` returns the regex captured group 1 which contains the filename to be downloaded from the header

What file did your code output it as, as I feel it will have messed with that

**Comment by TheFrenchGhosty** [comment]
@Emersont1 You're right, the file is named `None`... though I guess it's better than the script just crashing on it.

**Comment by TheFrenchGhosty** [comment]
Follow up: I now have downloaded my whole collection (962GB) - except the stuff that got outputted to `errors.txt`, this file was the only one causing an issue.

**Comment by Emersont1** [comment]
@TheFrenchGhosty I've opened #29, can you test this code to see if that fixes the issue please
