### ISSUE TITLE
What is the .json file used for? (games)

### ISSUE THREAD

**Issue by lem6ns** [Emersont1/itchio#32]
![image](https://user-images.githubusercontent.com/62519659/158911588-7db73fd4-e6b1-4df7-9693-bd871053a666.png)

**Comment by Emersont1** [comment]
The .json file contains details about the game, designed to aid in archiving

**Comment by lem6ns** [comment]
> The .json file contains details about the game, designed to aid in archiving

Ok, is there an app/visualizer that scans folders and displays them nicely?

**Comment by lem6ns** [comment]
> You'd have to create one, unfortunately
> 
> I'm happy to pitch in with this when I have time, and if you need any changes to the JSON format, I've an open PR/Discussion in #30

Made a repo, it'll be written in Neutralino and Svelte.
lem6ns/itchiodl-viewer

**Comment by Emersont1** [comment]
moved to #44
