### ISSUE TITLE
Bundle tool not working

### ISSUE THREAD

**Issue by BastienKovac** [Emersont1/itchio#33]
Hi,

The Bundle tool doesn't seem to be working on my end. After inspection it seems like, although the logging in request returns a HTTP code 200, the authentification isn't working properly. (Printing the scrapped HTML shows that it expects a logged in session).

I'm not quite sure why (I'm not used to work with web stuff), but it seems the session is not stored. I'm on Windows

Let me know if you need any more information

**Comment by Emersont1** [comment]
are you getting the same errors as in #34?

**Comment by BastienKovac** [comment]
Yes it was indeed the same error originally. I cloned the repo and manually changed the files to put my specific values, but then got a similar error later on
