### ISSUE TITLE
Download free games with this tool?

### ISSUE THREAD

**Issue by wertercatt** [Emersont1/itchio#49]
Maybe add the ability to input a link to a game page, like https://etra-etra-games.itch.io/vortex-an-fps-where-you-cant-damage-enemies for example, so that you can download games that aren’t able to be added to your library.

**Comment by wertercatt** [comment]
Adding onto this issue: being able to just throw creator pages like https://etra-etra-games.itch.io/ at the tool and have it download everything it freely can would be great too.

**Comment by wertercatt** [comment]
> Maybe add the ability to input a link to a game page, like https://etra-etra-games.itch.io/vortex-an-fps-where-you-cant-damage-enemies for example, so that you can download games that aren’t able to be added to your library.

Figured out how to get the game_id for arbitrary itch.io game pages. Just append [/data.json](https://etra-etra-games.itch.io/vortex-an-fps-where-you-cant-damage-enemies/data.json) to the url. If the game has free downloads, they'll appear in the [/games/game_id/uploads](https://api.itch.io/games/301585/uploads) endpoint with no key required.

**Comment by wertercatt** [comment]
> Adding onto this issue: being able to just throw creator pages like https://etra-etra-games.itch.io/ at the tool and have it download everything it freely can would be great too.

As for getting all the game pages from a creator, it looks like just scrapping the creator page for all <a class="title game_link"> hrefs should work sufficiently.

**Comment by Emersont1** [comment]
> As for getting all the game pages from a creator, it looks like just scrapping the creator page for all <a class="title game_link"> hrefs should work sufficiently.

This would probably be better achieved with the API, I'm loathed to do any scraping that isn't a last resort as it less likely to remain stable

**Comment by wertercatt** [comment]
> > As for getting all the game pages from a creator, it looks like just scrapping the creator page for all  hrefs should work sufficiently.
> 
> This would probably be better achieved with the API, I'm loathed to do any scraping that isn't a last resort as it less likely to remain stable

I haven’t found a way to get all games by a user with the api.

**Comment by Emersont1** [comment]
The PR needs some work for it to work, which I don't presently have time for. If you want to do the dev & testing work, i'll be more than happy to merge it in
