### ISSUE TITLE
Add Games in bundle to library does not work

### ISSUE THREAD

**Issue by GhostJumper** [Emersont1/itchio#54]
```
root@ca48796d249d:/# itch-load-bundle
Username: my@mail.com
Password:
Bundle URL: http://itch.io/bundle/download/4T80AvOSA70gkpyUhMNhaaghCbEY7J0DAJjWaWZd
Traceback (most recent call last):
  File "/usr/local/bin/itch-load-bundle", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/itchiodl/bundle_tool/__main__.py", line 13, in main
    b.load_games()
  File "/usr/local/lib/python3.10/site-packages/itchiodl/bundle.py", line 17, in load_games
    pages = int(s.select("span.pager_label a")[-1].text)
IndexError: list index out of range
root@ca48796d249d:/#
```

Did I use the Program as intended, or is this actually an issue?

**Comment by Emersont1** [comment]
It works as intended on my machine, are you running this on a datacenter IP (either a VPS or VPN) as I think it likes to block people when they do that

**Comment by GhostJumper** [comment]
It's running on the official python docker image on my local machine without any vpn.

**Comment by Emersont1** [comment]
That's weird, can you try in a venv, just as there may be weird docker shenangins going on.

https://docs.python.org/3/library/venv.html

**Comment by GhostJumper** [comment]
I tried it inside the official python docker with a venv. Same issue. I'll try it in a vm next.

**Comment by GhostJumper** [comment]
The outcome of running it on my Manjaro Laptop:

![Capture](https://user-images.githubusercontent.com/34964243/170892613-70efc4e7-5d60-4a75-b1dd-a628c49ee310.jpg)

The issue seems to not be caused by Docker after all.

**Comment by Emersont1** [comment]
it works on the latest version on my machine. how many pages is the bundle page?

**Comment by GhostJumper** [comment]
It has 34 pages (998 items)
