### ISSUE TITLE
Need to clean output name

### ISSUE THREAD

**Issue by pdughi** [Emersont1/itchio#6]
On windows, at least.

Too lazy to submit a PR, but this works:
Utils.py: 

```
def download_url(url, output_path, desc):
    with DownloadProgressBar(unit='B', unit_scale=True,
                             miniters=1, desc=desc) as t:
        output_path = re.sub(r'[\:\*\?\"\<\>\|]', ' ', output_path)
        urllib.request.urlretrieve(url, filename=output_path, reporthook=t.update_to)
```

**Comment by Emersont1** [comment]
Thanks
I forgot windows paths were more restrictive, I'll merge that in

**Comment by Emersont1** [comment]
Having had a look at it, I'm pretty sure all of the paths came out of the API as clean paths for the downloads

Is there any specific examples where the paths are in an invalid form coming out of the API

**Comment by pdughi** [comment]
Without linking to a specific page, one pdf had a question mark at the end of the file name.

**Comment by pdughi** [comment]
> Without linking to a specific page, one pdf had a question mark at the end of the file name.

Ah, found it;  https://reefsharkivist.itch.io/what-dont-you-do  note the comment section that indicates other folks had problems with this file as well, but it was fixed.

**Comment by Emersont1** [comment]
yeah, I just saw the comments, and that it applies to the official itchio client. I'm not sure if it's worth escaping for future cases, as I've not encountered any others that do this

**Comment by Emersont1** [comment]
I'll PR this code in for the 2.0 release
