### ISSUE TITLE
Neither regular downloader or bundle downloader work correctly.

### ISSUE THREAD

**Issue by StarFluxGames** [Emersont1/itchio#7]
Not sure what I'm doing wrong, but I can't seem to get these working. Regular downloader always fails after page 3, and bundle downloader won't even start.

![image](https://user-images.githubusercontent.com/20834597/157209664-561955a6-acf0-418d-b24b-08c7d789582b.png)
![image](https://user-images.githubusercontent.com/20834597/157209689-9ac4a549-c6fb-4114-a2dd-5c3870833d66.png)

**Comment by Emersont1** [comment]
I have fixed both, it's now called `bundle_tool`
